services:
  pyroscope:
    image: grafana/pyroscope:latest@sha256:6e8084763afe8e362ff16342b5c019dfa00c6ca6e85ba2dce81af38b4c6afbb2
    ports:
      - "4040:4040"

  grafana:
    image: grafana/grafana:latest@sha256:e932bd6ed0e026595b08483cd0141e5103e1ab7ff8604839ff899b8dc54cabcb
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - pyroscope

  tempo:
    image: grafana/tempo:latest@sha256:837b53999a8fbb662392ff44da0a4f5f074315ef916248e7396a6ddd2dfe4fc9
    command: [ "-target=all", "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"   # tempo
      - "4318:4318"   # otlp http
    depends_on:
      - redpanda

  redpanda:
    image: redpandadata/redpanda:latest
    ports:
      - "9092:9092" # Kafka API for clients
    command: >
      redpanda start --overprovisioned
      --mode=dev-container
      --smp=2
      --kafka-addr=PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr=PLAINTEXT://redpanda:9092

  # this is a hack to force there to always be a topic with 2 partitions so the example works
  # todo: remove this once we properly always set the partitions correctly
  redpanda-init:
    image: redpandadata/redpanda:latest
    depends_on:
      - redpanda
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        # Wait for Redpanda to be ready
        until rpk cluster info --brokers redpanda:9092 2>/dev/null; do
          echo "Waiting for Redpanda to be ready..."
          sleep 2
        done
        # Create topic with a partition if it doesn't exist and then add 1 to force 2 total
        rpk topic create tempo-ingest --partitions 1 --brokers redpanda:9092 || true
        rpk topic add-partitions tempo-ingest --num 1 --brokers redpanda:9092 || true
        echo "Topic tempo-ingest created with 2 partitions ... probably"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v3.5.0@sha256:b2cbdd93dee412142f95a61488118f33b8e31ea576bfb3ce625fbaffbdf0803a
    environment:
      - CONFIG_FILEPATH=/etc/redpanda/redpanda-console-config.yaml
    volumes:
      - ./redpanda-console.yaml:/etc/redpanda/redpanda-console-config.yaml
    ports:
      - "8070:8080"
    depends_on:
      - redpanda
  spring-opentelemetry-agent-example:
    build:
      context: ..
      dockerfile: examples/spring-opentelemetry/Dockerfile
    environment:
      # launch the pyroscope profiler as a java agent
      JAVA_TOOL_OPTIONS: -javaagent:/opt/pyroscope-agent.jar
      APPLICATION_NAME: spring-opentelemetry-agent-example
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
      PYROSCOPE_APPLICATION_NAME: spring-opentelemetry-agent-example
      OTEL_SERVICE_NAME: spring-opentelemetry-agent-example
      OTEL_JAVAAGENT_DEBUG: "true"
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://tempo:4318/v1/traces
      DEBUG: "true"
    ports:
      - "8080:8080"
    depends_on:
      - pyroscope
    restart: on-failure

  spring-opentelemetry-agent-classpath-example:
    build:
      context: ..
      dockerfile: examples/spring-opentelemetry/Dockerfile
    environment:
      LOADER_PATH: libs,/opt/pyroscope-agent.jar
      # launch the pyroscope profiler as a java agent
      JAVA_TOOL_OPTIONS: -javaagent:/opt/pyroscope-agent.jar
      APPLICATION_NAME: spring-opentelemetry-agent-classpath-example
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
      PYROSCOPE_APPLICATION_NAME: spring-opentelemetry-agent-classpath-example
      OTEL_SERVICE_NAME: spring-opentelemetry-agent-classpath-example
      OTEL_JAVAAGENT_DEBUG: "true"
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://tempo:4318/v1/traces
      DEBUG: "true"
    ports:
      - "8081:8080"
    depends_on:
      - pyroscope
    restart: on-failure

  spring-opentelemetry-classpath-example:
    build:
      context: ..
      dockerfile: examples/spring-opentelemetry/Dockerfile
    environment:
      LOADER_PATH: libs,/opt/pyroscope-agent.jar
      APPLICATION_NAME: spring-opentelemetry-classpath-example
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
      PYROSCOPE_APPLICATION_NAME: spring-opentelemetry-classpath-example
      OTEL_SERVICE_NAME: spring-opentelemetry-classpath-example
      OTEL_JAVAAGENT_DEBUG: "true"
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://tempo:4318/v1/traces
      DEBUG: "true"
    ports:
      - "8082:8080"
    depends_on:
      - pyroscope
    restart: on-failure
